/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author anit
 */
public class Add_Flights extends javax.swing.JFrame {

    /**
     * Creates new form Add_Flights
     */
    public Add_Flights() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        scrollPane1 = new java.awt.ScrollPane();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        com2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        com1 = new javax.swing.JComboBox<>();
        dom = new javax.swing.JCheckBox();
        intl = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dep = new javax.swing.JTextField();
        arr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fcode = new javax.swing.JComboBox<>();
        tcode = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jScrollPane1.setViewportView(jTextPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        popupMenu1.setLabel("popupMenu1");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/fli4.jpeg"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText(" Flight ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 68, 101, 31);

        jLabel3.setText(" Flight");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 117, 38, 25);

        com2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DUBAI INTERNATIONAL AIRPORT(DXB)", "KOCHI INTERNATIONAL AIRPORT(COK)", "THIRUVANANTHAPURAM INTERNATIONAL AIRPORT(TRV)", "ABU DHABI INTERNATIONAL AIRPORT(AUH)", "BENGALURU INTERNATIONAL AIRPORT(BLR)", "CHENNAI INTERNATIONAL AIRPORT(MAA)", "BAHRAIN INTERNATIONAL AIRPORT(BAH)", "MUSCAT INTERNATIONAL AIRPORT(MCT)", "INDIRA GANDHI INTERNATIONAL AIRPORT(DEL)" }));
        com2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com2ActionPerformed(evt);
            }
        });
        getContentPane().add(com2);
        com2.setBounds(409, 162, 228, 27);

        jLabel4.setText(" From");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 161, 46, 26);

        com1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KOCHI INTERNATIONAL AIRPORT(COK)", "DUBAI INTERNATIONAL AIRPORT(DXB)", "THIRUVANANTHAPURAM INTERNATIONAL AIRPORT(TRV)", "ABU DHABI INTERNATIONAL AIRPORT(AUH)", "BENGALURU INTERNATIONAL AIRPORT(BLR)", "CHENNAI INTERNATIONAL AIRPORT(MAA)", "BAHRAIN INTERNATIONAL AIRPORT(BAH)", "MUSCAT INTERNATIONAL AIRPORT(MCT)", "INDIRA GANDHI INTERNATIONAL AIRPORT(DEL)" }));
        com1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com1ActionPerformed(evt);
            }
        });
        getContentPane().add(com1);
        com1.setBounds(84, 162, 243, 27);

        dom.setText("Domestic");
        dom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domActionPerformed(evt);
            }
        });
        getContentPane().add(dom);
        dom.setBounds(94, 117, 92, 23);

        intl.setText("International");
        getContentPane().add(intl);
        intl.setBounds(204, 117, 112, 23);

        jLabel5.setText("To");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(354, 160, 43, 28);

        jLabel6.setText(" From Airport Code");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 288, 134, 26);

        jLabel7.setText(" To Airport Code");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 322, 134, 26);

        fid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fidActionPerformed(evt);
            }
        });
        getContentPane().add(fid);
        fid.setBounds(150, 68, 224, 31);

        jLabel10.setText(" Scheduled Departure");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 208, 134, 31);

        jLabel11.setText("Scheduled Arrival");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 245, 134, 31);
        getContentPane().add(dep);
        dep.setBounds(160, 210, 252, 26);
        getContentPane().add(arr);
        arr.setBounds(160, 247, 252, 26);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADD FLIGHTS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 19, 123, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(81, 400, 73, 29);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(174, 400, 100, 29);

        jLabel12.setText(" Price");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 359, 134, 16);

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price);
        price.setBounds(200, 354, 110, 26);

        jLabel9.setText("INR");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(166, 359, 28, 16);

        fcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DXB", "TRV", "AUH", "BLR", "MAA", "BAH", "MCT", "DEL", "COK" }));
        fcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcodeActionPerformed(evt);
            }
        });
        getContentPane().add(fcode);
        fcode.setBounds(166, 289, 85, 27);

        tcode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DXB", "TRV", "AUH", "BLR", "MAA", "BAH", "MCT", "DEL", "COK" }));
        getContentPane().add(tcode);
        tcode.setBounds(166, 322, 85, 27);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/fli5.jpeg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -80, 850, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void com2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com2ActionPerformed

    private void com1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com1ActionPerformed

    private void fidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fidActionPerformed

    private void domActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Add_Flights obj1=new Add_Flights();
obj1.setVisible(false);
admin obj=new admin();
obj.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  String s1  =fid.getText();
  String s2  =dep.getText();
  String s3  =arr.getText();
  String s6  =fcode.getSelectedItem().toString(); 
  String s7  =tcode.getSelectedItem().toString(); 
  String s5  =price.getText();
  String dept=com1.getSelectedItem().toString();     
  String arrl=com2.getSelectedItem().toString();     
   
            
        try {  
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql:///user","reenu","merryboy"); 
            java.sql.Statement stmt=c.createStatement();  
            if(dom.isSelected())
                stmt.executeUpdate("INSERT INTO add_flights " +"VALUES('"+s1+"','domestic','"+dept+"','"+arrl+"','"+s2+"','"+s3+"','"+s6+"','"+s7+"','"+s5+"')");
            if(intl.isSelected())
                stmt.executeUpdate("INSERT INTO add_flights " +"VALUES('"+s1+"','international','"+dept+"','"+arrl+"','"+s2+"','"+s3+"','"+s6+"','"+s7+"','"+s5+"')");
            c.close();
                
        }          
          catch (ClassNotFoundException ex) {     
              ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
                } 
        JOptionPane.showMessageDialog(null, "FLIGHT ADDED"); 
        Add_Flights obj=new Add_Flights();
        obj.setVisible(false);
        admin obj1=new admin();
        obj1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arr;
    private javax.swing.JComboBox<String> com1;
    private javax.swing.JComboBox<String> com2;
    private javax.swing.JTextField dep;
    private javax.swing.JCheckBox dom;
    private javax.swing.JComboBox<String> fcode;
    private javax.swing.JTextField fid;
    private javax.swing.JCheckBox intl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTextField price;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private javax.swing.JComboBox<String> tcode;
    // End of variables declaration//GEN-END:variables
}
